### ISSUE TITLE
Multimovies plugin issue

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#102]
Hope you're doing well,
Multimovies plugin is not working properly, the vidhide and streamwish servers are needed to reload many a times for it to work which is so time consuming and makes the plugin useless, it is not working despite using GitHub proxy, it works for some times but mostly it doesn't work. Hope you update it soon. If it's working perfect for you then please tell me the required setup settings in the app for it to work fine. 
Thanks

**Comment by SaurabhKaperwan** [comment]
> Hope you're doing well,
> Multimovies plugin is not working properly, the vidhide and streamwish servers are needed to reload many a times for it to work which is so time consuming and makes the plugin useless, it is not working despite using GitHub proxy, it works for some times but mostly it doesn't work. Hope you update it soon. If it's working perfect for you then please tell me the required setup settings in the app for it to work fine. 
> Thanks

Use dns or vpn

**Comment by phisher98** [comment]
No issue with plugin it could be a source issue also try to change DNS settings on router or VPN
