### ISSUE TITLE
Kind Request

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#103]
What's Up !
I would like you to add v-cloud and pixeldrain links to Hollywood movies too and series in your streamplay plugin, it would be great !
Thanks

**Comment by phisher98** [comment]
That's not how it works v cloud is getting extracted from Vegamovies whatever they are hosting you could request a source to be added

**Comment by Politecoder** [comment]
No, the v-cloud and pixeldrain links are being extracted from luxmovies as they are only showing up in hindi movies but VegaMovies is still not added as it also supports v-cloud and pixeldrain links for Hollywood movies so by that, I meant that you should also VegaMovies in you extension...

**Comment by phisher98** [comment]
Yes Vegamovies, Lux movies is added in Streamplay

**Comment by Politecoder** [comment]
Yes, will you add it ?

**Comment by phisher98** [comment]
Vegamovies is already added

**Comment by phisher98** [comment]
If you want it separately then you can use CSX Repo it has separate extension for Vegamovies and Luxmovies

**Comment by Politecoder** [comment]
> Vegamovies is already added

But whenever I try to play Hollywood movies, the links do not liad from VegaMovies

**Comment by phisher98** [comment]
Will look into it once I get a new machine

**Comment by phisher98** [comment]
Vega movies is added in CSX separately use it may not work on Stream play anymore
