### ISSUE TITLE
Anime dekho

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/HindiProviders#106]
Some old anime cartoons like shin chan have only vidstream links but vidstream link isn't found in you extension.

**Comment by phisher98** [comment]
Send me a video or screenshot

**Comment by Chani-rajat** [comment]
![Screenshot_20240807-205817](https://github.com/user-attachments/assets/a884c88d-73a2-4af8-baab-23c52b8e3fdb)
It's not working.

**Comment by phisher98** [comment]
![Screenshot_2024-08-07-21-10-28-607_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/461f3880-f8fd-43ee-b207-acf0dc040736)
![Screenshot_2024-08-07-21-11-11-511_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/1e761244-e985-4b7f-82d3-67a5c4f71722)

It's working 

1.Make sure you are on Pre release version 
2.try to use DNS change/VPN

**Comment by Chani-rajat** [comment]
Yes it worked when DNS is set to 
*NONE*
I use Cloudfare Dns👍🏻
