### ISSUE TITLE
Trustable Site Request 

### ISSUE THREAD

**Issue by Moviellect** [phisher98/HindiProviders#108]
Please add **9xflix** website in repo. This website is trustable.

![Screenshot_2024-08-11-07-21-52-41](https://github.com/user-attachments/assets/29bf0c32-05d8-4dd9-98a0-58031e8260ba)

**Comment by phisher98** [comment]
Provide the URL of the source

**Comment by phisher98** [comment]
URL not provided

**Comment by Moviellect** [comment]
https://9xflix.cc/
