### ISSUE TITLE
PR Movies: "no links found"

### ISSUE THREAD

**Issue by Shubham-dhyani14** [phisher98/HindiProviders#109]
When I try to play any movie, an alert saying "no links found" is shown and movie doesn't play. 
Only a few movies are playable <10%.
But on main site in browser the movies are playable.

**Comment by phisher98** [comment]
Hi Can you Give example which Series/Movie is working ?

**Comment by Shubham-dhyani14** [comment]
> Hi Can you Give example which Series/Movie is working ?

Those which have season-episode shows and not movies .
Like this 
(![image](https://github.com/user-attachments/assets/38c99ab1-bfa9-4453-9802-000de34706d1))

[https://prmovies.my/betty-la-fea-the-story-continues-2024-season-1-hindi-dubbed-amazon-prime-Watch-online-full-movie/](url)

**Comment by Shubham-dhyani14** [comment]
But now I find out that YoMovies is complete clone of PrMovies  and I can use it as alternative.

**Comment by phisher98** [comment]
Fixed
