### ISSUE TITLE
Add This Site

### ISSUE THREAD

**Issue by Nexus-Gits** [phisher98/HindiProviders#11]
Please add this site------

https://moviesmod.lol/
https://mlsbd.shop/
https://anime-world.in/
https://happy2hub.eu/

**Comment by phisher98** [comment]
1.Its same like TopMovies or UHDMovies already in Codestream try those if you think there streaming speed is good will think about adding it by exp its not that great for streaming for me try it once 
2.Not a Good source its not constant and reply on others links or sources in a file
3.Already Toonstream and Animedekho and Anplay is available under Movierulzhd for Hindi Animes
4.No Fap and already NSFW Extensons available
