### ISSUE TITLE
please fix uhdmovies addon

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/HindiProviders#110]
please fix the default config, at least let we choose quality and worker please please please the default worker never work.

**Comment by phisher98** [comment]
Whats the issue ?

**Comment by phisher98** [comment]
No Reply Kindly raise another issue

**Comment by nguyenquocngu93** [comment]
> Whats the issue ?

we can't choose quality and cf worker bro

**Comment by nguyenquocngu93** [comment]
![Screenshot_2024-08-31-18-56-10-291_com discord](https://github.com/user-attachments/assets/7bbf2990-6f49-48d4-ac3d-c22e6db3fa4d)
here 
This is an example of how uhdmovie should work, each resolution consists of many different workers
it comes from aniyomi's uhd source but I don't like using unofficial sources so hopefully you can fix cloustream's uhd source to look like that

**Comment by phisher98** [comment]
@nguyenquocngu93 I have tried to get all servers with different qualities try it out and if it doesn't play

1.reload the links and then try 
2.try VLC player 
3.try on website if link its working fine and redirecting properly 
4.Report the issue with series name/movie
