### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#112]
https://filmycity.blog/
Please check this site it has all direct links and no extra efforts required, hope you find this usefull.
Thanks

**Comment by phisher98** [comment]
Source is very dyamic not a good source redirecting to other websites

**Comment by Politecoder** [comment]
No problem, just wanted to tell rather creating an separate issue that bollyflix was working perfectly fine in streamplay but after update it stopped completely and in multimovies if you try to play latest movies such as 'horald and the purple crayon' it won't play, if you can then please fix them.
Thanks

**Comment by phisher98** [comment]
Bollyflix is workingits just download links stopped orking after update you can use VLC to play them

**Comment by phisher98** [comment]
@Politecoder Fixed Multi Issue

**Comment by Politecoder** [comment]
Thanks a lot Brother
