### ISSUE TITLE
Desicinemas link not found 

### ISSUE THREAD

**Issue by OshekharO** [phisher98/HindiProviders#113]
Please fix link not found issue on Desicinemas extension when you get time.

**Comment by sidrockzz98** [comment]
Can you add also add Playdesi in Desicinemas? 
Desicinemas has movies, Bollyzone has TV and this one has web series. Desicinema will finally be complete now. 

https://playdesi.net/playdesi/

**Comment by sidrockzz98** [comment]
Maybe it doesn't work because I have never seen tvlogy, dailymotion and netflix links in streamplay. Can you please check
