### ISSUE TITLE
Direct download support 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#117]
Add download support in extension's like this 

Akamai cdn = no download support through browser or cs3
Movierulzhd source = download support but it's a lot slow 

Hdmovie2 have download support in its site, and it's quite fast, can you able to add that fast download from cs3

Like megix did in moviesmod ( instant download) , or vegamovies (v-cloud download) like this 

This gonna help user to download, movies faster and doesn't gonna have restrictions or bandwidth or speed, user can able able to just select hold download button and then select instant download one, to download faster though cs3 or just open in browser function to download using browser

**Comment by phisher98** [comment]
That's not How it works Those extension gives those options as they are not streaming source instead download and stream sources and that is not available in these sources also Akamai download and other works it's slow in some as it's a source bandwidth limitation not extension or your ISP related issue.
![Screenshot_2024-08-17-17-08-44-916_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/a450b2b5-ca7b-4010-a25c-8831843624f2)

**Comment by Krishna-art-dev** [comment]
Thanks for information
