### ISSUE TITLE
MultiMovies Plugin Issue

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#118]
Multimovies vidhide server is not working, like when you try to play despicable me 4 it shows no links found. Please fix it.
Thanks

**Comment by phisher98** [comment]
Fixed

**Comment by Politecoder** [comment]
Brother but it's not still working for me

**Comment by phisher98** [comment]
Reload links

**Comment by Politecoder** [comment]
Can you please tell me the name of the DNS you are.using ?

**Comment by phisher98** [comment]
None I don't use CS inbuilt dns Just using 1.1.1.1 on Router

**Comment by Politecoder** [comment]
Thanks brother it's.working now !

**Comment by Mrunknow3** [comment]
> None I don't use CS inbuilt dns Just using 1.1.1.1 on Router 

How to use 1.1.1.1 in router?

**Comment by phisher98** [comment]
@Mrunknow3 use Google to find the solution
