### ISSUE TITLE
Streamplay Issue

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#122]
Links are getting extracted from VegaMovies for Hindi movies, but they are not getting extracted for series and Hollywood movies, please fix it.
Thanks

**Comment by Mrunknow3** [comment]
Also bollyflix doesn't working, add hdmovie2 to streamplay

**Comment by Politecoder** [comment]
Is there any response ?

**Comment by phisher98** [comment]
I don't have my machine no ETA

**Comment by nguyenquocngu93** [comment]
> Links are getting extracted from VegaMovies for Hindi movies, but they are not getting extracted for series and Hollywood movies, please fix it. Thanks

same issue, there's no link for series, mean while movies have plenty links
and after he fix moviesdrive, bollyflix disappear

**Comment by phisher98** [comment]
Can you mention some movies or series you are facing issue for ?

**Comment by Politecoder** [comment]
Like if you try to play winter Soldier or any Hollywood movies VegaMovies will not load and then if you try to play Aspirants(web series), it will also not extract those links

**Comment by phisher98** [comment]
I haven't added series support in Vegamovies yet so it will not load I will look into winter Soldier give me the URL

**Comment by nguyenquocngu93** [comment]
> I haven't added series support in Vegamovies yet so it will not load I will look into winter Soldier give me the URL

no bro, this hindo serie was load from topmovies, not vega, he said that vega will not load any shows
i hope he can fix it,

**Comment by Politecoder** [comment]
> I haven't added series support in Vegamovies yet so it will not load I will look into winter Soldier give me the URL

https://vegamovies.pet/download-captain-america-the-winter-soldier-2014-dual-audio-hindi-bluray-480p-720p-1080p-2160p/

**Comment by phisher98** [comment]
Fixed

**Comment by phisher98** [comment]
That. Could be a load reason so use UHDmovies and other separately added Moviesdrive
