### ISSUE TITLE
MultiMovies Videos No Link Found 

### ISSUE THREAD

**Issue by codeiva4u** [phisher98/HindiProviders#124]
**Title:**  

**Description:**

**Comment by codeiva4u** [comment]
I would like to bring a problem to your attention. In the MultiMovies provider, when we try to play a movie ▶️, it shows the message "No Link Found," due to which the movie ⏯️ cannot be played.Please kindly fix this as soon as possible so that all users can have a better experience. 🙏🏻 Your cooperation will be greatly appreciated.

**Comment by Politecoder** [comment]
Just set streamplay as the default homepage and then try to play, it will work fine

**Comment by phisher98** [comment]
#123
