### ISSUE TITLE
Site Request MultiMovies 

### ISSUE THREAD

**Issue by codeiva4u** [phisher98/HindiProviders#125]
🌸 I would like to bring a problem to your attention. In the MultiMovies provider, when we try to play a movie ▶️, it shows the message "No Link Found," due to which the movie ⏯️ cannot be played.Additionally, I request you to consider adding hdmovie4u as a new provider so that we users can have more options and a better experience.Please kindly fix this as soon as possible so that all users can have an improved experience. 🙏🏻 Your cooperation will be greatly appreciated.

**Comment by phisher98** [comment]
#123
