### ISSUE TITLE
Please bring in SuperStream

### ISSUE THREAD

**Issue by Rinhak** [phisher98/HindiProviders#126]
Can you please bring in SuperStream source, it was really good and had a lot of variety.

SuperStream is the name of the source 

It has multiple languages with subtitles available in it, one can stream in 4k as well. Please kindly look into it 🙏🏻.

**Comment by phisher98** [comment]
It's same as Streamplay if you find any 4k sources let me know and I will try to add those in Streamplay and there is no separate source super stream it's just a name
