### ISSUE TITLE
Site Request : Primewire

### ISSUE THREAD

**Issue by salman731** [phisher98/HindiProviders#127]
**Title:**  
Primewire

**Description:**  
https://www.primewire.tf/

**Source Language:**  
Multi Language

**Comment by phisher98** [comment]
Sure will look into it

**Comment by phisher98** [comment]
Not a Stable source when working on it it got down and server is unresponsive

**Comment by salman731** [comment]
No, it's stable 😔😔

**Comment by phisher98** [comment]
Added but Seach will not work as its protected with key and its dynamic code
