### ISSUE TITLE
Error in DhamerMovies (Streamplay).

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/HindiProviders#129]
**Anime : Trinity Seven**

Working Url directly taken from website 

> https://worker-mute-fog-66ae.ihrqljobdq.workers.dev/tvs/Trinity%20Seven/Season%201/Trinity%20Seven%20-%20S01E01%20-%20Administer%20and%20Third%20Selection%20Bluray-1080p%20%5BEN+JA%5D.mkv

Taken from cloudstream Streamplay and Codestream Source 

> https://worker-mute-fog-66ae.ihrqljobdq.workers.dev/tvs/Trinity Seven/Season 1/Trinity%20Seven%20-%20S01E01%20-%20Administer%20and%20Third%20Selection%20Bluray-1080p%20%5BEN JA%5D.mkv

### Differences:
First URL uses `%20` for spaces `Trinity%20Seven/Season%201/` and `+` in between `EN+JA` but the second doesn't.
`And the size also shows 15 B`.
![IMG_20240825_075032](https://github.com/user-attachments/assets/9fceea1a-3192-4e9f-9ec1-03d1e22907e8)
![Screenshot_2024-08-25-07-54-49-57_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/ba83a64c-371b-4668-bd27-a656674a8dc8)
```

**Comment by phisher98** [comment]
It could be a issue but all links are different and Source is also at rate limit
![image](https://github.com/user-attachments/assets/45442ce3-6d3d-465b-800c-931b384b70ec)

**Comment by nguyenquocngu93** [comment]
> It could be a issue but all links are different and Source is also at rate limit ![image](https://private-user-images.githubusercontent.com/153359846/363148809-45442ce3-6d3d-465b-800c-931b384b70ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjI0OTAsIm5iZiI6MTcyNjcyMjE5MCwicGF0aCI6Ii8xNTMzNTk4NDYvMzYzMTQ4ODA5LTQ1NDQyY2UzLTZkM2QtNDY1Yi04MDBjLTkzMWIzODRiNzBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNTAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzg2MjY5NmIwZGI2MWQwZDE1NjFhMThhZTc0NGRiNThjNDRmZWM2OTI2NGRkYTBkODAxMTQ5MDZhY2EwNWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jKZrFjpebEl7pBdDd1ksNGwahudg4UqMYnFVCwg5zGs)

Dahmermovie, Its not rare limit anymore, its official dead now, pls change domain to : https://a.datadiff.us.kg/

**Comment by phisher98** [comment]
Changed Kindly create a New Issue 

Once Issue CLosed No action will be taken on Closed Issues
