### ISSUE TITLE
Desi Cinemas/Bollyzone Buffering

### ISSUE THREAD

**Issue by devanshuagarwal667** [phisher98/HindiProviders#133]
Bollyzone/Desi Cinemas is buffering because only one source is there tvlogy hd.Earlier there used to be many sources and if one causes issue we can change that but now only one source is there please fix it.

**Comment by phisher98** [comment]
Give Example

**Comment by devanshuagarwal667** [comment]
i use this plugin for cloudstream for all hindi tv serials like tmkoc, kbc etc earlier there used to be 3 to 4 provider which bollyzone.tv uses but now there is only one provider tvlogyhd 2 and that source buffers a lot please provide other sources also which are already there in bollyzone website

**Comment by devanshuagarwal667** [comment]
> Give Example which Series/movie

i use this plugin for cloudstream for all hindi tv serials like tmkoc, kbc etc earlier there used to be 3 to 4 provider which bollyzone.tv uses but now there is only one provider tvlogyhd 2 and that source buffers a lot please provide other sources also which are already there in bollyzone website

**Comment by devanshuagarwal667** [comment]
> Give Example which Series/movie

![Screenshot_2024-09-01-14-33-55-451_com brave browser](https://github.com/user-attachments/assets/1cfd674f-0592-4c03-87ef-41997b4c94b9)
You can check this

**Comment by devanshuagarwal667** [comment]
> Give Example which Series/movie

Earlier around 2 to 3 month ago there were many provider but after that there was only one and uptil one week ago tvlog was working fine even now also in website it works fine but while using it in cloudstream it buffers

**Comment by devanshuagarwal667** [comment]
> Give Example which Series/movie

Heh Now no links found coming what to do now

**Comment by phisher98** [comment]
Fixed

**Comment by devanshuagarwal667** [comment]
> Fixed if you don't see all then try to reload links sometimes source is unstable

No when i uninstalled clound stream and installed again and then add repo using Hindirepo then this time when i play there is showing no streams found earlier it used tvlog but this time no streams found

**Comment by devanshuagarwal667** [comment]
> Fixed if you don't see all then try to reload links sometimes source is unstable

yes it is fixed now thank you very much
