### ISSUE TITLE
Bollyflix+ streamplay

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/HindiProviders#135]
please bring back bollyflix to streamplay, this server disappear about 2 months.

currently working servers on streamplay
Movies 
- uhd (only new movies)
- dahmer
- moviesdrive (only some movies) 
- moviesapi/multi embed : low quality 
- nollyver (very very slow, can't stream)

Tv shows:
- moviesapi / multi embed 
- uhd (new series)
- moviesdrive TV show no working

**Comment by phisher98** [comment]
[CSX](https://github.com/SaurabhKaperwan/CSX) Added Bollyflix and Moviesdrive seprately as Streamplay couldn't load all the links and gets bugged sometimes so now will add seprate extensions
