### ISSUE TITLE
Live TV (all are working, I checked just now)

### ISSUE THREAD

**Issue by Rachitidk** [phisher98/HindiProviders#139]
1. TᴀᴛᴀPIay M3U PLAYLIST

https://yuvraj43.xyz/tp/tplay.m3u
> Indian

https://yuvraj49.vercel.app/tataplay-ww.m3u
> Worldwide

https://tplay-live.vercel.app
>  Web

2. Jiotv.be M3U PLAYLIST

https://amitb3669.github.io/jiobe11.m3u

3. https://tgaadi-web.tech/TP/playlist.m3u?Join=@tataplayonline 
> Both

4. https://amitb3669.github.io/b1gg.m3u 
> I don't remember

5. https://allinonereborn.com/tataplay 
> Web India

6. https://allinonereborn.com/livetv-web 
> Web world

`CS4 usual template will lack features, most imp ones are like epg guide & additon of epg from outer link, remove specific category & channel as there are too many etc.`. You should try playing in ott navigator, tivimate u will surely notice.

**Comment by phisher98** [comment]
Send it here only

**Comment by phisher98** [comment]
okay i think you can just ask which channel you need and i will try to find links myself and add it if i will able to find link for it

**Comment by phisher98** [comment]
Cool
