### ISSUE TITLE
Codetrream not working without vpn

### ISSUE THREAD

**Issue by aadio7** [phisher98/HindiProviders#14]
Idk why.. It suddenly shows error after click on any movie or series

**Comment by phisher98** [comment]
Use 1.1.1.1 as dns or vpn it's a ISP issue

**Comment by aadio7** [comment]
> Use 1.1.1.1 as dns or vpn it's a ISP issue

Whih website is for pixel drain links??

**Comment by phisher98** [comment]
It's fetching from different sources it's not a single source

**Comment by aadio7** [comment]
> It's fetching from different sources it's not a single source

So pixel drain fetching links from different source.. Okay..

**Comment by aadio7** [comment]
> It's fetching from different sources it's not a single source

Btw i cant find multimovies 1080p or multimovies.. I can only see multimovies 480p.. You can check in true detective

**Comment by phisher98** [comment]
Yeah it says 480 but its 1080 i will check once i got time how i can get it to mention 1080 not 480

**Comment by aadio7** [comment]
> Yeah it says 480 but its 1080 i will check once i got time how i can get it to mention 1080 not 480

Thanks for helping.. And maybe you can also add topmovies for series also

**Comment by phisher98** [comment]
Create a Request Issue for it maybe
