### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by salman731** [phisher98/HindiProviders#140]
**Title:**  
Smashystream

**Description:**  
Movies and series with multiple sources and languages (https://smashystream.com/)

**Source Language:**  
Multiple

**Comment by phisher98** [comment]
This could take time as i am not able to find how to get token

**Comment by Zafor7869** [comment]
https://mkvcinemas.cat/
https://cinedoze.com/
https://fibwatch.online/
https://rtally.vercel.app/
 
Bro, please do add these site in your cloudstream playlist when you get free time. Just visit these websites once.

**Comment by salman731** [comment]
I will look into this...

**Comment by phisher98** [comment]
Unable to Add till we get Token Protection
