### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by Kira0116** [phisher98/HindiProviders#142]
**Title:**  
Cinevood

**Description:**  
https://1cinevood.click/  Direct 1080p links with wide range of multi Content and fast updates 🔥
(Better than UHD and moviesdrive 🌚)

**Source Language:**  
Hindi+Multi

**Comment by phisher98** [comment]
I will add it in Streamplay are you okay with that ?

**Comment by Kira0116** [comment]
Aboustely Fine but it would be better as separate provider 🙂

**Comment by phisher98** [comment]
Okay I will add it Separately

**Comment by SaurabhKaperwan** [comment]
> Okay I will add it Separately 
> Have you requested this on other Devs Repo as well if yes let me know as we don't want multiple devs working on same source

Did u check this website? I just saw some movies and series and they have many different structures

**Comment by Kira0116** [comment]
> Okay I will add it Separately Have you requested this on other Devs Repo as well if yes let me know as we don't want multiple devs working on same source

No i didn't

**Comment by phisher98** [comment]
@SaurabhKaperwan Yeah I saw some movies and series but i think its not that difficult to navigate it add separately need to check once i get back

**Comment by SaurabhKaperwan** [comment]
@phisher98  check old movies or series like 4-5 months old u will get what I'm saying

**Comment by phisher98** [comment]
@SaurabhKaperwan Got your point Then I may not add this it's very dynamic and some of links don't even work and Source is very slow

**Comment by phisher98** [comment]
@Kira0116 As Saurabh Dev said its very Dyamic if even added it have mostly same Links as UHD or Moviesmod or Moviesdrive let me know which you are able to find in this and cant get it in Other Extensions
