### ISSUE TITLE
Plugin request

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#143]
https://hdhub4u.contact/
Can you please add this site separately in your repo ?
Please reply if you will otherwise a 'No' will be appreciable.
Thanks

**Comment by phisher98** [comment]
It was added in CSX and then removed as most of its links already present in Moviesdrive and others so he removed it you can ask Dev to add it back if he thinks its needed

**Comment by Politecoder** [comment]
Ok no issues
