### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by Nexus-Gits** [phisher98/HindiProviders#144]
**Title:**  
Drmlive

**Description:**  
All in one live tv channel website. A better and reliable live tv source : https://drmlive.in/

**Source Language:**  
Multiple

**Comment by phisher98** [comment]
What's the source of this website ? Is there any telegram channel ? I want to know because source should be reliable if anything happens it will be fixed or replaced

**Comment by salman731** [comment]
What it means source of site.My telegram or source telegram ?

**Comment by phisher98** [comment]
So I want to ask how you got the source of website

**Comment by phisher98** [comment]
Update:
Only Sony Liv links Working without any Protection 
JioTv links are protected
Tata Play links are loading but CS Exoplayer is giving Black Screen issue not a Extenion Issue

This will be closed as of now and Indian TV Extension source is in Maintaince right now will update once its back
