### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Kira0116** [phisher98/HindiProviders#147]
Not a serious one but if you can please change the posters of streamblasters in continue watching section i think thay have stopped posting movie covers so everytime I watch something it shows some red poster it's a little inconvenient 🥲

**Comment by phisher98** [comment]
Can you send me a Screenshot of what are you talking about ?

**Comment by phisher98** [comment]
Okay I think i know what you mean but it can't be Fixed as Source Doesn't contain any Poster that can be placed in that Poster Place so its a Source Issue
