### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#148]
**Title:**  

**Description:**  

**Source Language:**  

https://movies4u.poker/
Please add this site(It Contains everything with great resumable server), and please do reply if you are gonna add it or not.
Thanks

**Comment by phisher98** [comment]
Added in StreamPlay

**Comment by Politecoder** [comment]
Thanks a lot !

**Comment by Politecoder** [comment]
Can you please add it separately

**Comment by phisher98** [comment]
If u want it separately you can request on CSX Provider

**Comment by phisher98** [comment]
Its working for most of content if i do changesit may not work for other

**Comment by Politecoder** [comment]
Ok

**Comment by phisher98** [comment]
Now it will work Fix pushed

**Comment by Politecoder** [comment]
Thanks again !

**Comment by Politecoder** [comment]
I just checked, it's all working fine now, thanks a lot !

**Comment by Politecoder** [comment]
Few suggestions and improvements:
When you try to play series like Loki, while playing the first episode you will see that 480p v-cloud and pixeldrain links are loaded first and after waiting so much it loads 1080p links(v-cloud and pixel), can you please reverse it otherwise so that first 1080p links are loaded...
Thanks

**Comment by phisher98** [comment]
That's not possible mate it executes each function so it totally random you can use Priority to set Quality play first and Just wait till loading finishes

**Comment by Politecoder** [comment]
Bro like when we try to play the movie The Matrix in streamplay through v-cloud or pixeldrain links, it starts playing other parts of the movie, same as in some series I think it gets confused with similar names of movies and episodes and sometimes play the wrong things, is it fixable ?

**Comment by phisher98** [comment]
I am not seeing any can you screen record it ?

**Comment by Politecoder** [comment]
Uploading recording-20240919-222107_4QqpjeYN.mp4…

**Comment by Politecoder** [comment]
As you can see when I try to play the episode it plays a different movie of relating name...

**Comment by phisher98** [comment]
Bro This source doesn't support Series and by seeing it going down again and again may not add support yet

**Comment by Politecoder** [comment]
Sure no issues

**Comment by phisher98** [comment]
![image](https://github.com/user-attachments/assets/7d77db85-0f9f-41ac-92d5-b46b8bb10264)

**Comment by Politecoder** [comment]
But as you see for the first episode of any series it is not loading from VegaMovies but for the nest episode it starts loading from VegaMovies, same with all the series...

**Comment by Politecoder** [comment]
No issues, you can leave it, other servers are also there

**Comment by Politecoder** [comment]
Bro one suggestion, remove movies4u for series as it is messing it up by playing movies in place of episodes and all as not supported and just keep it for movies..
