### ISSUE TITLE
Site Request - Simillar to AnimeDekho

### ISSUE THREAD

**Issue by garouthe** [phisher98/HindiProviders#149]
Hi
can you add below sites. looks like animedekho sister sites. so should be simillar process

also can you update new server 'oplayer' in animedekho also. (you will find in below link)
https://animedekho.net/episodes/jujutsu-kaisen-1x1/

sites request
1st
One Pace
https://onepace.me/

**Description:**  
One Piece Anime Without Filler and Good Pacing - One Pace Fan Project

**Source Language:**  
English Dub, English Sub (both)

2nd
HindiSubAnime
https://hindisubanime.co/

**Description:**  
Anime in Hindi Subtitles - Fan Subs

**Source Language:**  
Hindi Sub

**Comment by SaurabhKaperwan** [comment]
Onepace is already available in avacado repo

**Comment by phisher98** [comment]
Okay I will look at it
