### ISSUE TITLE
add topmovies for series also

### ISSUE THREAD

**Issue by aadio7** [phisher98/HindiProviders#15]
For series also add this source

**Comment by aadio7** [comment]
@phisher98 bhaiya discord pe ek msg bheja h..coding nhii aati prr observation h

**Comment by phisher98** [comment]
Added Series in TopMovies

**Comment by aadio7** [comment]
> Added Series in TopMovies

Bro not working.. Only loading.. Tried with dns and vpn.. Other sources load and play

**Comment by phisher98** [comment]
These Links are not reliable as it's Downloading links not streaming if you use VLC it will work but sometimes you can't seek forward this source so keep that in mind

**Comment by aadio7** [comment]
> These Links are not reliable as it's Downloading links not streaming if you use VLC it will work but sometimes you can't seek forward this source so keep that in mind

Okay.. I will keep in mind
