### ISSUE TITLE
Time4tv doesn't working

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/HindiProviders#151]
![Screenshot_2024-09-18-20-24-00-106_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/user-attachments/assets/abe1e1d5-47dc-437b-80df-c37b5faab9dd)

I try almost 6-7 all have the same error.

**Comment by phisher98** [comment]
Thats a Source Issue 

Kindly check Website before creating a Issue
