### ISSUE TITLE
Streamplay enhancement 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#152]
https://github.com/user-attachments/assets/d3d98717-58bf-482f-ae06-d0f6ba588dfd

![IMG_20240918_225601](https://github.com/user-attachments/assets/87b95da2-39b7-48d8-a08a-0236bd85f54e)
Can you able to turn that, small cap tags to, first Letter capital one? Like this Material Arts, Superhero, Mecha, Giant Robot 
![IMG_20240918_225616](https://github.com/user-attachments/assets/a9d380bd-18b6-4902-8772-3ca120c7b9d9)
Or you can't as it provided by tmdb, If can't close this issue 

Thanks

**Comment by phisher98** [comment]
Request Fulfilled

**Comment by Krishna-art-dev** [comment]
> Request Fulfilled

Thanks bro, now homepage looks much better
