### ISSUE TITLE
UHDmovies Error (Bug)

### ISSUE THREAD

**Issue by OtakuVadER** [phisher98/HindiProviders#155]
UHDmovies 

Uhdmovies Vlc  gives parser container error and uhdmovies resume gives network connection error 

![Screenshot_2024-09-20-12-37-38-90_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/e41f794e-bde6-4cb6-8f7b-25491eac1388)
![Screenshot_2024-09-20-12-37-45-67_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/61aaf97f-18d8-4348-8e7a-539c52f74d43)

**Comment by phisher98** [comment]
Try to play it again if it still doesn't play then use VLC as Player 
![IMG_20240920_124607](https://github.com/user-attachments/assets/007d01ae-dbba-4920-81f9-a17de04d8737)
![Screenshot_2024-09-20-12-45-02-963_org videolan vlc](https://github.com/user-attachments/assets/9aedd660-2aec-4ece-a85f-7e150039fcb5)

**Comment by OtakuVadER** [comment]
I copied link and played using network stream since I don't use vlc and it worked that way !

**Comment by phisher98** [comment]
It sometimes work and sometime Doesn't with Inbuild so you have to try it once or twice to get it played

**Comment by phisher98** [comment]
![Screenshot_2024-09-20-12-54-26-936_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/962c8716-c637-4d4e-9cb8-4cb9bb1ab5be)
Check it out

**Comment by OtakuVadER** [comment]
Alright!
