### ISSUE TITLE
Streamplay v25 issue

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/HindiProviders#157]
### Details

Uhdmovies source disappear after update, tested with:
Blind twice, trap, furiosa, his three daughters, uglies, the crow, longlegs, maxxxine, borderlands.....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its a Issue so you should have selected Report Issue 

Looking into it now

**Comment by phisher98** [comment]
Fixed make sure to choose correct Issue to raise the correct issue

**Comment by nguyenquocngu93** [comment]
I will remember

**Comment by phisher98** [comment]
No Problem Thanks for Reporting

**Comment by nguyenquocngu93** [comment]
> Looking into it now

![Screenshot_2024-09-21-21-56-19-851_com dl lagradost cloudstream3](https://github.com/user-attachments/assets/07c51ec1-e0d5-49b6-98e3-2d2f4ce7596a)

Working with uhdmovies addon but not show up any link in streamplay 

https://github.com/user-attachments/assets/9b9884ac-0f77-43c2-a868-42204bb09508

**Comment by phisher98** [comment]
ahh okay but yeah its working use VLC if you get issues to play

**Comment by nguyenquocngu93** [comment]
It's okay now, thank you
