### ISSUE TITLE
Allmovieland enhancement 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#158]
### Details

Allmovieland.fun is a gimik website which doesn't provide access to all its movies

There's an actual original website of allmovieland that provides full access, add that one 

![Screenshot_2024-09-21-21-48-15-74_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/7f173feb-1c09-45e7-95a7-29720df36c63)
You can check this website for, referer header

Actual allmovieland website (https://keels313ale.com/play/tt15560806)
It uses IMDb I'd, but that screenshot website uses tmdb how, they done that idk 

Edit ( it doesn't matter tmdb or IMDb )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
No this is a Completely different source and it only has Skin like Moviesland
Also Its Quality and Source is not that Great or reliable so Will not be Added this
Let me know if you have any questions

**Comment by Krishna-art-dev** [comment]
> No this is a Completely different source and it only has Skin like Moviesland Also Its Quality and Source is not that Great or reliable so Will not be Added this Let me know if you have any questions

That screenshot isn't the main website 
Main website is that link (https://keels313ale.com/play/tt15560806) this

**Comment by Krishna-art-dev** [comment]
> > No this is a Completely different source and it only has Skin like Moviesland Also Its Quality and Source is not that Great or reliable so Will not be Added this Let me know if you have any questions
> 
> That screenshot isn't the main website Main website is that link (https://keels313ale.com/play/tt15560806) this

That was just to get referer header or this won't gonna work, because idk how to get that

**Comment by phisher98** [comment]
Yes I have checked https://keels313ale.com/play/tt15560806 only

**Comment by phisher98** [comment]
Yes buddy i have checked https://keels313ale.com/play/tt15560806 this is also like an API but its not AllMoviesland API

**Comment by Krishna-art-dev** [comment]
> Yes I have checked https://keels313ale.com/play/tt15560806 only

Umm a lot before I told you About allmovieland app, that provides access to all movie, they use this website 

Allmovieland.fun doesn't have kung fu panda 
But their app have it 

That's allmovieland api, they get their movies from that website, let me provide you with some more info wait

**Comment by phisher98** [comment]
Okay so you want to add this instead of that

**Comment by Krishna-art-dev** [comment]
> Okay so you want to add this instead of that

Yes, that will provide access to all movie sources that present in allmovieland app or main website 

![Screenshot_2024-09-21-22-15-36-47_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/5198767d-f75e-4305-a2c5-5529f57c4dac)

**Comment by phisher98** [comment]
ahhh I can do that

**Comment by Krishna-art-dev** [comment]
> ahhh I can do that but only in Streamplay

No problem, do that, so that we gonna get all movie present in that, umm some guys want to watch movies in low quality without buffer and allmovieland is a good source for that 

So yes do that

**Comment by phisher98** [comment]
Okay

**Comment by Krishna-art-dev** [comment]
> Okay

Thanks

**Comment by phisher98** [comment]
Bro I have just checked its already like that when creating it we already got to know about api and also added Syamic change for API domain so we don't need changing again and again

**Comment by Krishna-art-dev** [comment]
> Bro I have just checked its already like that when creating it we already got to know about api and also added Syamic change for API domain so we don't need changing again and again

Means you already added that? Means added original allmovieland server?

**Comment by phisher98** [comment]
Yes
