### ISSUE TITLE
miruro.tv

### ISSUE THREAD

**Issue by mpaunovic** [phisher98/HindiProviders#159]
### Source name

Miruro

### Source link

https://www.miruro.tv/

### Source language

English

### Other details

Could you please add this source? Here's the Github page:

https://github.com/Miruro-no-kuon/Miruro

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Its already requested on other repo I have checked also its getting sources from Gogoanime new domain

**Comment by phisher98** [comment]
Duplicate #161
