### ISSUE TITLE
Issue Report

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#160]
https://github.com/user-attachments/assets/8d0d5d8e-7642-405e-800a-8a1e69050c89

As you might be seeing, you can also check for other series, it doesn't extract links from VegaMovies for the first episode but works fine from the next episode, if you can then please fix it..
Thanks

**Comment by phisher98** [comment]
![image](https://github.com/user-attachments/assets/9a3d3ea3-2490-45ec-9052-c90ba9a97e28)
This could be a problem so i don't think i could get it work skill issue

**Comment by phisher98** [comment]
Remember to select correct Category for Report Issue next time

**Comment by Politecoder** [comment]
Sure

**Comment by Politecoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/153359846/369691820-9a3d3ea3-2490-45ec-9052-c90ba9a97e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTQzNDQsIm5iZiI6MTcyNzAxNDA0NCwicGF0aCI6Ii8xNTMzNTk4NDYvMzY5NjkxODIwLTlhM2QzZWEzLTI0OTAtNDVlYy05MDUyLWM5MGJhOWE5N2UyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNDA3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGRiZGYxZTYxZTNmM2QxNDY2M2YyN2ViMjE4ZjVkYWY2MmNjOWEyZmU4ZjBhNTMwMzI1N2IwYWVlZjY4ODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dCtJwo61YUQHAYreOYyutDfB0TU7lVkmTkeFUgcM1jI) This is the problem

No issues by the way thanks by the way you had a skill issue a few moments but now you figured it and fixed thanks bro ! 😃

**Comment by phisher98** [comment]
Yeah i updated my skill after debugging hahahahaha

**Comment by phisher98** [comment]
I have added more sources for this

**Comment by Politecoder** [comment]
Thank you so much bro !!

**Comment by Politecoder** [comment]
I am about to cry 😂 now some series like The Boys stopped extracting from VegaMovies..can understand this is so tedious..just leave it or if you can then please see it in your free time..can understand I am being so irritating 😂, but I am so irresistive to have the source in streamplay working without issues, if it works I swear I will not bother you for anything else..
Thanks

**Comment by phisher98** [comment]
I will check but one thing will jink other and if this work it could jinkx other

**Comment by phisher98** [comment]
Done Fixed

**Comment by Politecoder** [comment]
Thanks brother

**Comment by phisher98** [comment]
Also you can keep reporting issue but create a new issue further

**Comment by Politecoder** [comment]
Sure
