### ISSUE TITLE
Streamplay search issue

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#164]
### Source Name

Streamplay 

### Source language

Hindi 

### Steps to reproduce

Can't able to find some movies in streamplay 

Like = stree and agent, etc... name forgot ( doesn't show in streamplay search) 

I think you get what I am saying, 

### Expected behavior

Streamplay should show movie 

### Actual behavior

Doesn't show movies

### CloudStream Version

Red version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
You have to sometime use space after name or try to use year after it try it

**Comment by Krishna-art-dev** [comment]
> You have to sometime use space after name

Tried

**Comment by phisher98** [comment]
Working for me

**Comment by Krishna-art-dev** [comment]
> Working for me

Umm screenshot?

**Comment by phisher98** [comment]
![Screenshot_2024-09-24-12-07-43-726_com lagradost cloudstream3 prerelease-edit](https://github.com/user-attachments/assets/6aec6a5f-2cab-4c2f-acc7-ba7f3d2fa9ee)

**Comment by Krishna-art-dev** [comment]
> ![Screenshot_2024-09-24-12-07-43-726_com lagradost cloudstream3 prerelease-edit](https://private-user-images.githubusercontent.com/153359846/370161029-6aec6a5f-2cab-4c2f-acc7-ba7f3d2fa9ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjAyNzAsIm5iZiI6MTcyNzE1OTk3MCwicGF0aCI6Ii8xNTMzNTk4NDYvMzcwMTYxMDI5LTZhZWM2YTVmLTJjYWItNGMyZi1hY2M3LWJhN2YzZDJmYTllZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwNjM5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2RjNjEzZjNjMzEwMjY4ZGEwZDRiNWM5M2U5MTA1MTViMGFiNDE2YjkyYTgwZjFjOWZhYWE0ZTY0YzI2NDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wG1D2RTx3ozlN3yvteOiXZ6UBEVTejVuTplkN3dMe1Y)

Ooh got it what I was doing wrong, first when I searched, it removed my space then I add space and  search when first result showed and it worked

**Comment by Krishna-art-dev** [comment]
Still agent one didn't worked

**Comment by phisher98** [comment]
em hm if you don't get result use year and still it doesn't it could be a issue with tmdb

whats agent ? give me full name

**Comment by Krishna-art-dev** [comment]
> em hm if you don't get result use year and still it doesn't it could be a issue with tmdb
> 
> what agent ? give me full name or reference

https://www.themoviedb.org/movie/886436-agent

**Comment by Krishna-art-dev** [comment]
Got issue 
![Uploading Screenshot_2024-09-24-12-38-58-52_e4424258c8b8649f6e67d283a50a2cbc.jpg…]()

**Comment by Krishna-art-dev** [comment]
> Yup but i have also find a solution you try to use its Regional name

Like how, what should I search

**Comment by phisher98** [comment]
ఏజెంట్

**Comment by phisher98** [comment]
![image](https://github.com/user-attachments/assets/52f30358-5000-4c54-b80f-c68b1d1d5fc5)

**Comment by phisher98** [comment]
Checked its fetching the sources fine as well

Closing this now

**Comment by Krishna-art-dev** [comment]
Hmm where do I find it, mostly everywhere movie title is agent, and Google also doesn't show regional title

**Comment by phisher98** [comment]
TMDB Data

**Comment by Krishna-art-dev** [comment]
> TMDB Data
> 
> Search this ఏజెంట్

I got movie, but tmdb doesn't showed that movie in first place, I use trakt to get that movie link that I shared here

If I doesnt get movie in tmdb how can I able to get it's original title, this is the problem

**Comment by phisher98** [comment]
I can't help with that

**Comment by Krishna-art-dev** [comment]
> I can't help with that

😐 Hmm, can you able to add switch to trakt to get movie title, because trakt provides tmdb I'd, also it's recommended is good as well

Then you won't have to change a lot of things, 
First we get movie title from trakt
Then trakt tmdb I'd 
Then everything that's happening now

**Comment by phisher98** [comment]
It doesn't work like that when you search it gets first page results only and as checked your Title/Movie is on 7th Page as it's title is very common so either i can let it be like this or get results till 10 pages which will get a lot of resullts to go through

**Comment by Krishna-art-dev** [comment]
> It doesn't work like that when you search it gets first page results only and as checked your Title/Movie is on 7th Page as it's title is very common so either i can let it be like this or get results till 10 pages which will get a lot of resullts to go through

Hmm then leave it, 10 page results are a lot, and other sources have this

**Comment by phisher98** [comment]
Yup
