### ISSUE TITLE
Einthusan.tv

### ISSUE THREAD

**Issue by kiskey** [phisher98/HindiProviders#167]
### Source name

Einthusan.tv 

### Source link

https://einthusan.tv

### Source language

Hindi,Telugu,Malayalam,Tamil

### Other details

This is primarily a movie site. This site supports all  HD content movies, with embedded subtitles for most of the recent movies and has very good collection of content by year sorted and by language sorted,  for the major Indian languages. Support this as site and add it to part of streamplay api, would be a great addition.

This does not seem to contain cloudflare or i have not encountered cloudflare wall . .This site is pretty stable and streams are blazing fast.

This site is primarily targeting western countries and it may not load in India. But looks like the website looks for geolocation , could be manipulated to pass the region and location to some random city in USA with country as US. This  i could see from browser source inspect and it kind of carries the api with geolocation information,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
![Screenshot_2024-09-25-08-46-44-865_com android chrome-edit](https://github.com/user-attachments/assets/12f2265f-84ed-4548-af06-162cedd3117d)

**Comment by aravinddwara** [comment]
We will use vpn
