### ISSUE TITLE
Wvc crashing on playback 

### ISSUE THREAD

**Issue by Jamess661** [phisher98/HindiProviders#169]
### Source Name

Uhdmovies 

### Source language

Hindi

### Steps to reproduce

When casting video web video cast using UHD movie plugin and selecting CF works files play it back begins but only for a few minutes before crashing back to the home screen on web video caster
![Screenshot_20240923-085123](https://github.com/user-attachments/assets/5f5d5fa5-406f-4692-be6f-2c11b0c76746)
![Screenshot_20240925-075128](https://github.com/user-attachments/assets/e6b2fb3e-5ee2-4fce-8cdc-59f4949ce6b8)

### Expected behavior

I expected the file to play like all the other files 

### Actual behavior

But for whatever reason it seems to crash so random and the times are not the same it could be a minute it could be 40 seconds

### CloudStream Version

Red version latest update 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Use VLC player to play it

**Comment by phisher98** [comment]
It's not a Extension issue in my opinion try to create a issue on app repo
