### ISSUE TITLE
Pixel drain or moviedrive serious error

### ISSUE THREAD

**Issue by aadio7** [phisher98/HindiProviders#17]
while i open any series and links load .. it has a lot of 1080p but actually.. for ex i open load link for episode 1 for a series but its shows a lot of 1080p link with different size.. but actually of the 1080p links is for that episode1 other 1080p links are for episode 2,3,4.... but it shows all the lijnks in 1st episode and similar case for other episode a lot of 1080p links.. Now you have to find everytime which link for that episode 
![image](https://github.com/phisher98/HindiProviders/assets/147267681/7b38b5d1-f09f-4fb3-94d4-94a24f43b9db)

**Comment by phisher98** [comment]
Can you provide example of show you are trying

**Comment by aadio7** [comment]
> Can you provide example of show you are trying also I have not added series support on Movie Drive yet so that's maybe the reason you are seeing that I will check that just me show name on which you are seeing this bug

It's for mostly shows bro.. like heeramandi,Ripley, chacha vidhayak hai hamare,goodbye earth.. till now checked only these 4 shows and all of these have this problem.. so it's for all shows I
think

**Comment by aadio7** [comment]
> Can you provide example of show you are trying also I have not added series support on Movie Drive yet so that's maybe the reason you are seeing that I will check that just me show name on which you are seeing this bug

Hey did you fix it??

**Comment by aadio7** [comment]
> Can you provide example of show you are trying also I have not added series support on Movie Drive yet so that's maybe the reason you are seeing that I will check that just me show name on which you are seeing this bug

Now I cant see pixeldrain and moviedrive links In those series .. this also become hit and miss like others .. you can check it in Ripley,heeramandi..

**Comment by phisher98** [comment]
Check now

**Comment by aadio7** [comment]
> Check now

Still can't see it in any other webseries previously it has...😅

**Comment by aadio7** [comment]
> Check now

Still can't see it in any webseries

**Comment by aadio7** [comment]
> Check now

I cant see it in any series..heeramandi,Ripley, chacha vidhayak hai hamare,goodbye earth

**Comment by phisher98** [comment]
![image](https://github.com/phisher98/HindiProviders/assets/153359846/8bf4c6ac-9025-47cf-b5a7-a88a16ebd7e3)
Sometimes it can hit and miss depend on time

**Comment by aadio7** [comment]
> ![image](https://private-user-images.githubusercontent.com/153359846/328206484-8bf4c6ac-9025-47cf-b5a7-a88a16ebd7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTI5ODUsIm5iZiI6MTcxNTAxMjY4NSwicGF0aCI6Ii8xNTMzNTk4NDYvMzI4MjA2NDg0LThiZjRjNmFjLTkwMjUtNDdjZi1iNWE3LWE4OGExNmViZDdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmE4OTczOTRmMGM3YWJlNmE0OTIzNzZjYzJiZWQ1ODJmMWQ4MzVlYjYzZjZmMWQyODQ0OGU5YmZiZmMzNDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xVRpGQ_9K25sGnxnkrP06tZ2tlLcetXHm3rgkt7COS8) Sometimes it can hit and miss depend on time

Thanks bhaiya now it's visible

**Comment by phisher98** [comment]
Its already there but it can be wonky because of source so you can try it

**Comment by aadio7** [comment]
> Its already there but it can be wonky because of source so you can try it

Can you solve the isp problem by anything.. it's a big problem since I can't able to use dns or VPN in tv... If you can't solve it it's also okay.. I will watch on tablet

**Comment by phisher98** [comment]
Not possible we have to wait or ask dev to include proxy support 

also you can change DNS on Router settings and change it to 1.1.1.1

**Comment by aadio7** [comment]
> Not possible we have to wait or ask dev to include proxy support
> 
> also you can change DNS on Router settings and change it to 1.1.1.1

It's okay I solved the problem.. change my firestick dns manually...
