### ISSUE TITLE
What's Different between streamplay and streamplay lite

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#172]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Streamlite have less sources to load from Streamplay
