### ISSUE TITLE
Site request in Streamplay 

### ISSUE THREAD

**Issue by nguyenquocngu93** [phisher98/HindiProviders#173]
### Source name

Cinemalux 

### Source link

https://cinemaluxe.click/

### Source language

Hindi, English 

### Other details

Why i want this:

This is an example with the movie "dadio"

![Screenshot_2024-09-27-07-28-18-017_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/00d5f7b5-0fcb-423b-9280-176cacb4ae46)

![Screenshot_2024-09-27-07-27-59-810_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/7ac53fac-83bd-453b-bf6f-780c63a42394)

Cinemalux have 4k for this, and Streamplay doesn't , plus moviemod always doesn't work.

Cinemalux separate Addon doesn't support imdb, hard to find subtitle 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the any Dev Repo or Request.
- [X] I have checked that the extension does not already exist by searching on CS and verified it.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
Very limited content available on it

**Comment by phisher98** [comment]
I have added 1 more source and Fixed Modlfix a little

**Comment by nguyenquocngu93** [comment]
> Very limited content available on it
> 
> I am not able to find dadio

"Daddio", i wrote it wrong, thank for your respond
