### ISSUE TITLE
No links found on anime dekho

### ISSUE THREAD

**Issue by DRAGON0088897** [phisher98/HindiProviders#18]
Anime dekho isnt working

**Comment by phisher98** [comment]
Have you tried Anime Dekho 2 after doing bypass on website once  ? if not try that first

**Comment by phisher98** [comment]
Yes with 2nd one you have to bypass for 24 hr and then you can use in App

**Comment by phisher98** [comment]
Give it time till then if still then use Toonstream or Anplay
