### ISSUE TITLE
Unable to build, need help

### ISSUE THREAD

**Issue by dewxo** [phisher98/HindiProviders#20]
I'm newb!

 .\gradlew.bat AnimeDekhoProvider:deployWithAdb --info
Initialized native services in: C:\Users\devvr\.gradle\native
Initialized jansi services in: C:\Users\devvr\.gradle\native
The client will now receive all logging from the daemon (pid: 4796). The daemon log file: C:\Users\devvr\.gradle\daemon\7.4\daemon-4796.out.log
Starting 10th build in daemon [uptime: 9 mins 10.899 secs, performance: 100%]
Using 16 worker leases.
Now considering [D:\Github\HindiProviders] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file 'D:\Github\HindiProviders\settings.gradle.kts'.
Projects loaded. Root project using build file 'D:\Github\HindiProviders\build.gradle.kts'.
Included projects: [root project 'CloudstreamPlugins', project ':AllMovieLandProvider', project ':AnimeDekhoProvider', project ':Animenosub', project ':Anplay', project ':BanglaPlex', project ':CodeStream', project ':Cricket Streams', project ':Desicinemas', project ':FreeTVProvider', project ':IndianTVProvider', project ':Kissasian', project ':Movierulzhd', project ':ShowFlixProvider', project ':Streamblasters', project ':Supercartoons', project ':Toonstream', project ':Topcartoons', project ':UpMovies']

> Configure project :
Evaluating root project 'CloudstreamPlugins' using build file 'D:\Github\HindiProviders\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for root project 'CloudstreamPlugins' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for root project 'CloudstreamPlugins' as it is up-to-date.
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant
Using Kotlin Gradle Plugin gradle74 variant

> Configure project :AllMovieLandProvider
Evaluating project ':AllMovieLandProvider' using build file 'D:\Github\HindiProviders\AllMovieLandProvider\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':AllMovieLandProvider' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':AllMovieLandProvider' as it is up-to-date.

> Configure project :AnimeDekhoProvider
Evaluating project ':AnimeDekhoProvider' using build file 'D:\Github\HindiProviders\AnimeDekhoProvider\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':AnimeDekhoProvider' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':AnimeDekhoProvider' as it is up-to-date.

> Configure project :Animenosub
Evaluating project ':Animenosub' using build file 'D:\Github\HindiProviders\Animenosub\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':Animenosub' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':Animenosub' as it is up-to-date.

> Configure project :Anplay
Evaluating project ':Anplay' using build file 'D:\Github\HindiProviders\Anplay\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':Anplay' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':Anplay' as it is up-to-date.

> Configure project :BanglaPlex
Evaluating project ':BanglaPlex' using build file 'D:\Github\HindiProviders\BanglaPlex\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':BanglaPlex' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':BanglaPlex' as it is up-to-date.

> Configure project :CodeStream
Evaluating project ':CodeStream' using build file 'D:\Github\HindiProviders\CodeStream\build.gradle.kts'.
Caching disabled for Kotlin DSL accessors for project ':CodeStream' because:
  Build cache is disabled
Skipping Kotlin DSL accessors for project ':CodeStream' as it is up-to-date.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Github\HindiProviders\CodeStream\build.gradle.kts' line: 11

* What went wrong:
D:\Github\HindiProviders\local.properties (The system cannot find the file specified)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Watched directory hierarchies: []

**Comment by phisher98** [comment]
Join discord and Ask there can't do much here
