### ISSUE TITLE
Movie search option is not working properly in Superstream.

### ISSUE THREAD

**Issue by Rinhak** [phisher98/HindiProviders#22]
Steps to reproduce
Take any source (Superstream for example) and search for a movie in it
Constantly shows a blank screen no matter what.
Can't search a movie we want to watch.
Expected behavior
When you put a movie name you would expect the movie to come on screen. But it shows a blank screen no matter how much you search for it.

Actual behavior
Shows a blank screen everytime you search for a movie.

Cloudstream version and commit hash
4.3.2 ee4d1de

Android version
Android 14
![Screenshot_20240513_063643_CloudStream Beta](https://github.com/phisher98/HindiProviders/assets/99042103/dd37bbf2-e753-4472-9e60-6628efd17fcb)

**Comment by phisher98** [comment]
Wrong Repo this repo doesn't contain Superstream
