### ISSUE TITLE
AnimeDekho default source

### ISSUE THREAD

**Issue by garouthe** [phisher98/HindiProviders#23]
Hello

can you make vidstream default source for animedekho

streamwish is kinda slow for me

**Comment by DEMON7808** [comment]
Please help me 
I don't know how to install this repo in cloudsteam

**Comment by phisher98** [comment]
@garouthe you can use Profile to select the source priority for any help join discord and ask in Support section related to app

**Comment by phisher98** [comment]
@DEMON7808 Use Hindirepo in Add extension URL
