### ISSUE TITLE
animedekho link not found

### ISSUE THREAD

**Issue by garouthe** [phisher98/HindiProviders#24]
animedekho old shows link not found showing

fix vidstream plz

**Comment by phisher98** [comment]
Give an example and Vidstream is working fine

**Comment by garouthe** [comment]
> Give an example and Vidstream is working fine

error image:
https://ibb.co/Lr5Rbyf

try playing any shinchan or doraemon episode.
they changed player design that could be reason also

**Comment by phisher98** [comment]
Will check

**Comment by Rinki-Goyal** [comment]
I'm also facing the same issue, briefer description here:-


On Anime Dekho:

No Links Found
Remote error
NETWORK_ERROR_IO_NETWORK_CONNECTION_FAILED (2001
Source error

On Anime Dekho 2:

No Links Found

**Comment by phisher98** [comment]
Fixed
