### ISSUE TITLE
Hdmovie2 links not found

### ISSUE THREAD

**Issue by karanveers969** [phisher98/HindiProviders#25]
From all of the extensions hdmovie2 is the one that's stable and good in speed amd provides quality streams 

Recently , on playing a movie ot shows links not found whereas the website is working fine

**Comment by phisher98** [comment]
Checked Working Fine Posters are not working as Website poster are not visible

**Comment by karanveers969** [comment]
![Screenshot_2024-05-14-20-15-23-29_a153ad7195ab131f51b38ebe0eab4033](https://github.com/phisher98/HindiProviders/assets/135799357/f9c0f0f2-94fd-48a6-b355-1cd9b70d4adf)
Even used a vpn , showing links not found the same with likdev 256 
Pls check

**Comment by phisher98** [comment]
![image](https://github.com/phisher98/HindiProviders/assets/153359846/e02d72ab-d190-4077-9d9b-b817ae5f573d)


Select EP 1 and try with other Movies as welll

**Comment by karanveers969** [comment]
I've noticed an issue
The hdmovie2 extension from this repo shows no links found
Whereas the hdmovie2 from the hexated repo is working fine
Maybe this is only happening to me but pls try and check yourself that hexated one works whereas this repo 's hdmovie2 shows no link found
Period

**Comment by karanveers969** [comment]
@phisher98
