### ISSUE TITLE
Maintenance AnimeDekho

### ISSUE THREAD

**Issue by devvratmiglani** [phisher98/HindiProviders#31]
Looks like it broke again, last time they changed vidstream domain, not sure about this time.

**Comment by garouthe** [comment]
yes not working, and if you fix it please remove default 'streamwish 720p' it gives english audio and there is no track options to change. normal streamwish options has track options change.

**Comment by phisher98** [comment]
I can't remove Default you can use Priority feature to make source Priorityand any other issue you can ask in Discord

**Comment by devvratmiglani** [comment]
tq
