### ISSUE TITLE
HD and Multi provider

### ISSUE THREAD

**Issue by Kira0116** [phisher98/HindiProviders#32]
https://www.full4movies.credit/
Please add this site bro 🙏😄
Reply if your saw this.

**Comment by SaurabhKaperwan** [comment]
I already added this website to my repo : https://raw.githubusercontent.com/SaurabhKaperwan/CSX/builds/CS.json

**Comment by Kira0116** [comment]
> I already added this website to my repo : https://raw.githubusercontent.com/SaurabhKaperwan/CSX/builds/CS.json

Shows "No links" bro

**Comment by SaurabhKaperwan** [comment]
![Screenshot_2024-05-27-11-10-37-84_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/phisher98/HindiProviders/assets/91174352/61806deb-adaa-42e2-8e5c-dd55f71e08d0)

It is working

**Comment by phisher98** [comment]
@Kira0116 True His Extenion is Working I have tested it as well and looks Good to me you can use it and create a issue on his repo if yu get any issue with example which series/movie you are getting issue

**Comment by Rayforest** [comment]
> I already added this website to my repo : https://raw.githubusercontent.com/SaurabhKaperwan/CSX/builds/CS.json

How do I add your repo from this link?

**Comment by phisher98** [comment]
![image](https://github.com/phisher98/HindiProviders/assets/153359846/fbf72f0c-afff-4f3e-ad41-c561dbc0175f)
Add it here
