### ISSUE TITLE
DahmerMovies source not working

### ISSUE THREAD

**Issue by bean-factory** [phisher98/HindiProviders#33]
Any links from the dahmermovies source do not load, however looking through the code i found the website from which it sources which opens in the browser without any issues. I think the API used to scrape the data may be broken but I'm not well versed with the code enough to figure it out.

**Comment by phisher98** [comment]
Its not a Extension issue it maybe a CS Issue try to play it using VLC

**Comment by bean-factory** [comment]
How is it not an extension issue, the extension doesn't load a source does that not make it an extension issue? I can manually find the link and play it through vlc or cs sure but that doesn't involve the extension right?

**Comment by phisher98** [comment]
Give me an example which series or movie are you trying

**Comment by bean-factory** [comment]
https://github.com/phisher98/HindiProviders/assets/76696071/9183d53a-830d-4b5c-9c4a-0060077b3983

Any movie or series with DahmerMovies source doesn't load but most have other alternative sources so it's not a big issue but some shows like this have only source.

**Comment by phisher98** [comment]
Try it now

**Comment by phisher98** [comment]
@bean-factory Fixed https://github.com/phisher98/HindiProviders/commit/f2bab22470fc38d984a19a60cc21926f542e6a3d
