### ISSUE TITLE
Anime Dekho no links found

### ISSUE THREAD

**Issue by DestroyerBDT** [phisher98/HindiProviders#35]
[AnimeDekho](https://animedekho.net) gives an error when trying to play something

Error:
**No Links Found
Unexpected player error
ERROR_CODE_PARSING_MANIFEST_MALFORMED (3002)
Source error**

**Comment by garouthe** [comment]
hmm they changed player design for vidstream again

**Comment by dewxo** [comment]
Yeah, it is broken

**Comment by garouthe** [comment]
animedekho still not working for me
can anyone confirm?

**Comment by DestroyerBDT** [comment]
> animedekho still not working for me can anyone confirm?

It is working now ...
