### ISSUE TITLE
Req: www.braflix.video

### ISSUE THREAD

**Issue by krishus96** [phisher98/HindiProviders#37]
This extension is available in the "[Arabico](https://github.com/aymanbest/Arabico)" Plugin, but it is not working.

**Comment by phisher98** [comment]
Yeah so Its just like Codestream or Sora it gets Links from multiple sources and its encrypted with Keys I have also checked previous one its source is already added in Codestream or Sora so add this is not possible and can't add this if you are getting issues in Finding any Series or Movie and you are able to find it on any source you can request it.
