### ISSUE TITLE
Animedekho.net

### ISSUE THREAD

**Issue by StarCoplayz** [phisher98/HindiProviders#38]
Animedekho.net repository is working but I am opening a video to not link found I am trying all way to open but it's still not working please fix it..

**Comment by phisher98** [comment]
Which show/movie are you talking about all works for me

**Comment by DestroyerBDT** [comment]
> Which show/movie are you talking about all works for me

Example: Shin Chan, Doraemon
Both use VidStream

**Comment by DestroyerBDT** [comment]
Now, it's working good again

**Comment by phisher98** [comment]
![Screenshot_2024-06-05-19-10-10-91_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/d97ae6cd-3115-4937-9f37-d3086a58a4a0)
Working fine
