### ISSUE TITLE
TopmoviesR not showing 

### ISSUE THREAD

**Issue by aadio7** [phisher98/HindiProviders#39]
For topmovies... there is topmovies and topmoviesR link.. topmoviesR can be stream through cloudstream player whereas the other need vlc and no playback...in some movies and webseries topmoviesR not showing.. only topmovies showing

**Comment by phisher98** [comment]
Yes TopR is for Resume Download Links so it's available in some movies and series also series is a hit and miss because of sources code used on website so can't help with that.
