### ISSUE TITLE
AnimeDekho Problem

### ISSUE THREAD

**Issue by garouthe** [phisher98/HindiProviders#40]
Hi,

animedekho is not working for many people including me. I am on their telegram group and its not working for many.

I've attached video check it out.

v15 was working fine (just vidstream was not working). now in v16 no links found.

toonstream and anplay does not have much data as animedekho.

please check video

https://github.com/phisher98/HindiProviders/assets/162981112/d2e1b66f-e467-4463-92f0-aca68b7dbf8b

**Comment by phisher98** [comment]
It's working fine I guess it's your app use pre release it looks like it's a stable version so use pre release version if you have any other issues for CS then join discord and ask there
