### ISSUE TITLE
Multimovies Not Work Please Fix 

### ISSUE THREAD

**Issue by codeiva4u** [phisher98/HindiProviders#45]
![photo_2024-06-12_11-58-58](https://github.com/phisher98/HindiProviders/assets/153196182/be1b8c18-0b22-4304-b9b1-fa6c13592d12)

**Comment by codeiva4u** [comment]
Multimovies Not Work  And Added Please This https://hdmovies4u.fans/ Provider

**Comment by phisher98** [comment]
Duplicate
