### ISSUE TITLE
Uhdmovies 

### ISSUE THREAD

**Issue by aadio7** [phisher98/HindiProviders#49]
Aniyomi closed all their extension(including uhdm) so can you develop something like that..since in Hindi provider uhdmovies movies only show the only highest size file link.. series are also very confusing like they are not categoried as season and episode(also along with the size it's doesn't not show resolution in links in side

**Comment by phisher98** [comment]
Not possible I have just fixed previous extension and make it work  and Because of source complexity skill issue also already added uhdmovies in StreamPlay

**Comment by aadio7** [comment]
> Not possible I have just fixed previous extension and make it work and Because of source complexity skill issue also already added uhdmovies in StreamPlay

They got DMCA,,so take down every extension .. so maybe u can use their uhdmovies extension directly as your extension or somewhat since they tell that we can use third party extension in aniyomi sti

**Comment by phisher98** [comment]
Use Multimovies or StreamPlay They also have 4K Content also UHD movies is not reliable source


Will think about UHD

**Comment by aadio7** [comment]
> Use Multimovies or StreamPlay They also have 4K Content also UHD movies is not reliable source
> 
> Will think about UHD

Oh yeah now I see multimovies is back again.. but if you want uhdmovies apk .. I have I can send you on discord(14.19 and 13.19 both)

**Comment by phisher98** [comment]
That will not help in in coding it I will think about it no promises
