### ISSUE TITLE
Crichd doesn't work 

### ISSUE THREAD

**Issue by sonutiwari94** [phisher98/HindiProviders#50]
Crichd doesn't work

**Comment by phisher98** [comment]
Example ? Which is not working ?

**Comment by sonutiwari94** [comment]
Crichd, INDIAN TV, NOT WORKING SIR
PLEASE ADD MORE REPO LIKE
iBOMMA.movie
https://www.moviezwap.mba
iBOMMA.movie
https://www.mp4moviez.bingo/
filmyzilla.vg
SAICORD (BEST DUB SITE)

**Comment by phisher98** [comment]
1. CricHD is working sometime it may not its a source issue 
![image](https://github.com/phisher98/HindiProviders/assets/153359846/1f983f9b-7318-4992-8a29-56b06dfd7ae5)
2. INDIAN TV Working some channels or TATA may not working issue with source 
![image](https://github.com/phisher98/HindiProviders/assets/153359846/b29fcb72-80a0-4ac7-ac80-e40a028ef8b1)
3.https://www.moviezwap.mba not a Good Source and Limited Content (Better Alternative HDMovie,Movierulzhd)
4. iBOMMA.movie No Content only Information Bad Source
5. filmyzilla.vg same as 3 point
6. SAICORD (BEST DUB SITE) -Very slow and Limited Content
