### ISSUE TITLE
Anplay , Anime dekho and toonstream not working 

### ISSUE THREAD

**Issue by 1llusionxD28** [phisher98/HindiProviders#52]
Hello! So it's been a while I have been using Hindi providers, Anplay and animedekho were not working previously but yesterday toonstream also stopped working :(
I request you humbly to please fix them 
Thanks for your efforts and support!

**Comment by 1llusionxD28** [comment]
Hi , just asking do we need a prerelease version for Anplay to work?

**Comment by phisher98** [comment]
Yes Pre is Now Latest Version and use Pre going forward
