### ISSUE TITLE
Kissasian source and categories

### ISSUE THREAD

**Issue by testcs420** [phisher98/HindiProviders#53]
Add these categories please.
Sources in Kissasian all appear as "Kissasian" whereas sources in Kissasianv2 are properly labeled with resolution and source
```
        "drama-list/ongoing.html?page=" to "Drama Ongoing",
        "filter?type=1&status=2&country=1&sort=updated?page=" to "Korean Drama",
        "filter?type=2&status=2&country=1&sort=updated?page=" to "Korean Movies",
        "filter?type=1&status=2&country=2&sort=updated?page=" to "Japanese Drama",
        "filter?type=2&status=2&country=2&sort=updated?page=" to "Japanese Movies",
        "filter?type=1&status=2&country=5&sort=updated?page=" to "Chinese Drama",
        "filter?type=2&status=2&country=5&sort=updated?page=" to "Chinese Movies",
```

![1pb3qz](https://github.com/phisher98/HindiProviders/assets/173214438/a415fd18-64eb-4000-af16-6d7f5177d604)
![emvgs7](https://github.com/phisher98/HindiProviders/assets/173214438/9bcaa901-ac82-494d-afa0-f3b2bd967b98)

**Comment by phisher98** [comment]
Yeah Both of them are Different websites you can use any your choice

**Comment by testcs420** [comment]
Can you add the categories to v2 as well? They only appear in the one, preferably above the drama/mystery/variety categories and remove the "drama completed" category because its made redundant with the categories above
