### ISSUE TITLE
hdmovie2 doesn't work with movies

### ISSUE THREAD

**Issue by karanveers969** [phisher98/HindiProviders#55]
@phisher98 
hdmovie2 doesn't work with movies it shows no links found , ehen watching tv series the superplayer one shows no links found whereas ultrastream works 
![Screenshot_2024-06-20-21-12-21-44_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/135799357/2e2e757d-d5d4-4fd8-bfe6-01ddc2ba82a3)

**Comment by phisher98** [comment]
Its a Source Issue not a Extension issue on Website also its not loading

![image](https://github.com/phisher98/HindiProviders/assets/153359846/5c0bcb2c-0869-4d7c-84ee-3ab184d90763)

**Comment by karanveers969** [comment]
I am taking about the movies i already mentioned that web series work with
ultrastream but there's no solution for movies

**Comment by phisher98** [comment]
Okay i will look into it but its loading it but not playing it

**Comment by karanveers969** [comment]
Sure
