### ISSUE TITLE
Toonstream not working

### ISSUE THREAD

**Issue by DestroyerBDT** [phisher98/HindiProviders#56]
The [ToonStream website](https://toonstream.day) is up

**Comment by DestroyerBDT** [comment]
IDK if it was Cloudflare-protected before
If it was, then maybe another issue
If not then here's a [Cloudflare killer](https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/network/CloudflareKiller.kt)

**Comment by phisher98** [comment]
Need to wait till they remove cloudflare
