### ISSUE TITLE
Adding This Repo in Android TV

### ISSUE THREAD

**Issue by mpaunovic** [phisher98/HindiProviders#57]
Could you please make adding your repo to Cloudstream on Android TV easier?  It's hard to do it via copy/paste. A clickable link in the README.md that adds your repo automatically upon clicking would suffice, just like the ones below:

[Repos](https://rentry.org/cs3-repos)

Something like this:

`cloudstreamrepo://raw.githubusercontent.com/phisher98/HindiProviders/builds/HindiProviders.json`

Thank you.

**Comment by phisher98** [comment]
Use Shortcode "Hindirepo"

**Comment by mpaunovic** [comment]
It works! :smiley:

Maybe it's not the worst idea to make this short code easily accessible (in the readme for example) instead of it being buried deep within the closed issues. Just a thought.

Anyway, thank you so much and keep it up!
