### ISSUE TITLE
Hdmovie2 not working 

### ISSUE THREAD

**Issue by karanveers969** [phisher98/HindiProviders#59]
I am sorry if this is repetitive but 
Hdmovie2 used to work with series and movies but now it's loading it but not playing it 
If this is an invalid and unsolvable issue then kindly update me on this

**Comment by phisher98** [comment]
Unable to get the Root cause its not Playing

**Comment by karanveers969** [comment]
@phisher98 the extension is fixed now akmaicdn source works now
Closing the issue

**Comment by phisher98** [comment]
Thanks for notifying
