### ISSUE TITLE
Have questions and recommendations 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#6]
•> Does anyone from cs extension developer scrape app like in Sorastream there is cinematv api mean someone had scraped it before or cinematv owner himself gave it to use 

•> Why your repo link what worked before failed to work today and now when you sent it, it works again

•> Why allmovieland app have more movies then allmovieland official website
Can anyone able to scrape allmovieland app?

•> Like that I recently come across more three app which got my intrest

 

  • Cricfy tv 
     - have sports and a lots of love tv channel of can say a lot of iptv
     - Worth scraping this app, can't able to find from where it got that much iptv, in it's dns logs it had links ,it  connect to their streaming sites 
     - you check it, if it got your interest also
    
    • And one more request if this is already in extension.  or some extension like this exist in cs tell me it's name (Indian tv and tv? )

 • Dooflix this app is great i think ( For hindi movies and some hindi anime) 
    - No ads ( Using dns)
    - Have Good servers ( One is down Now but they are fixing it) only I cannot able to see kung fu panda because of down server 
    - have multiple servers 
    - good ui 
    - I don't know it can be scraped because of naginx I think

     • It's hard to get information about this site. It uses naginx and I don't know about it anything maybe app must have something that let it access it through app not through browser
         - dooflix.net
         - dooflixpanel.com
         - akamai.dooflix.net
         - dooflix.live
         - myhlsvideoplayer.com
         - oxoo.myhlsvideoplayer.com
         - streaminghlsplayer.com
         - hlsvideostreamplayer.com

This are the site it it connect to. I think there is more but gonna find about it later 

• movieshub 
   - Have no ads
   - lots of servers mean like 7-8 servers
   - I was right it has website and have lots of servers we need to ask to scrape this site 
> 
![Screenshot_2024-04-01-22-09-12-76_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/phisher98/HindiProviders/assets/121063162/1a1cf91b-be31-4bac-a1c0-c4032dfa60da)
![Screenshot_2024-04-01-22-09-19-14_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/phisher98/HindiProviders/assets/121063162/2f7ff8f2-1f82-4df7-bdbd-58e26039a02f)

   
• Allmovieland App
  - I think this can be scraped it's website have been scraped as you know 
  - it mostly uses same server that been used in its website telling from its player ui 
  - it connect to this server when playing allmovieland app and allmovieland site ( Movies not found on the app also connect to the same server )
          • casionest292flaudient.com ( it's multi audio server) 
  - And there is another sever there also can able to see in allmovieland salaar webpage 
  - https://casionest292flaudient.com/play/ftt13927994?d=allmovielandapp.app  an example of salaar which can be found in both app and website
  - https://casionest292flaudient.com/play/ftt1302011?d=allmovielandapp.app    this is an example of Kung fu panda stream which cannot be found in allmovieland website
  - https://watch.gxplayer.xyz/watch?v=S6Z9CVBJ this is also an example of Kung fu panda stream from different server ( same as salaar second server ) which means they have streams with multiple servers we just need to get it 

  - This is the download link for kung fu panda 2 https://download.bbupload.com/download?v=NICOKX63
  
  - it's there in Allmovieland server , we just need to know from where all that movies is getting indexed 
  - we this website https://adcdn1.site/

Now everything is getting out of my mind and also I don't know if it can be scraped or not so I will leave all that to you ask any dev, that it can be scraped of not 

I don't know the reasearch I am doing will gonna help or not so I will leave here 

Thanks 

And thanks going to sleep bye bye good night

**Comment by Krishna-art-dev** [comment]
Issue is messy right now will gonna fix it later

**Comment by Krishna-art-dev** [comment]
If there is any other good repo that isn't in mega repo like your repo please tell me it's name or send me it's link 
Thanks

**Comment by phisher98** [comment]
Most of these websites are already there in Sora and most of them are in there 

i was doing some changes so have deleted old json and created new 

You can create a new issue for any new website you want
