### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/HindiProviders#65]
Bollyflix not working on stream play and multimovie so buffering, can you add vega movies. 

Also toonstream not working.

**Comment by phisher98** [comment]
1.Bollyflix is Working 
![image](https://github.com/phisher98/HindiProviders/assets/153359846/849ae005-1fb6-4125-a2e8-97b653d86e3d)
2.Multimovie also works fine its a source issue but most of time it works fine
3.Toonstream added Cloudflare wait till removed and try alternative AnPlay,Tooniboy,AnimeDekho Etc

Create New Issue if have more issues once closed it will remain closed
