### ISSUE TITLE
AnimeDekho Not Working

### ISSUE THREAD

**Issue by SameerDeshmukh37** [phisher98/HindiProviders#68]
**AnimeDekho Provider** is Not Playing Anything Just Showing `No Links Found` When Trying To Play Anything. Please Fix That Asap.

_AnimeDekho Website is Working Totally Fine._

**Comment by phisher98** [comment]
![Screenshot_2024-06-28-11-22-06-94_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/065631a1-fb69-4f79-b356-854ca8ae885c)
Working fine make sure you are on latest pre release and even if still gives error try VPN or 1.1.1.1 tunnel app from Play Store you could also ask in discord server
