### ISSUE TITLE
Have questions 

### ISSUE THREAD

**Issue by Krishna-art-dev** [phisher98/HindiProviders#7]
From where did you learn to use kotlin and recommendations I am interested to learn it 

Why you deleted sources?

**Comment by phisher98** [comment]
This is not the place to chat Join CS Discord for any queries

**Comment by Krishna-art-dev** [comment]
> This is not the place to chat Join CS Discord for any queries

Server link please

**Comment by phisher98** [comment]
https://discord.com/invite/MTN7Ehej
