### ISSUE TITLE
AnimeDekho, Anplay no links

### ISSUE THREAD

**Issue by ryan4021** [phisher98/HindiProviders#71]
In AnimeDekho or Anplay, whenever I play a video in Cloudstream it says "No Links Found".

Anime World is working fine but they have a small collection of anime compared to Anime Dekho and Anplay.

I think fixing AnimeDekho would be enough cuz this site has almost every dubbed anime and cartoons.

**Comment by phisher98** [comment]
![Screenshot_2024-07-01-10-38-53-22_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/9007f1ed-aba2-4b4f-8436-b96998c77683)
![Screenshot_2024-07-01-10-30-00-76_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/05cdc8e4-6e68-4c58-8a1b-6b36caffa890)
![Screenshot_2024-07-01-10-29-52-16_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/1f6d8741-7e93-45fe-b364-00a1938d2be4)

Working fine 
1.use Pre release latest 
2.try vpn.
3.try to use 1.1.1.1 cloudflare app tunnel.
