### ISSUE TITLE
AnimeDekho "No Links Found"

### ISSUE THREAD

**Issue by ryan4021** [phisher98/HindiProviders#74]
AnimeDekho is not working, whenever I play a video it says "No Links Found"

**Comment by Mrunknow3** [comment]
Bro just delete hexated animedeko

**Comment by ryan4021** [comment]
I'm not using hexated repo.

**Comment by Mrunknow3** [comment]
That's your internet problem 

![Screenshot_2024-07-01-16-50-25-750_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/phisher98/HindiProviders/assets/154901963/375160cb-9477-422c-bfc7-81e02cbceec0)

Here working fine.

**Comment by phisher98** [comment]
@ryan4021 It's Working fine try VPN also update to latest pre release also there are Tooniboy,Toonstream,Anplay,animeword as well
