### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ryan4021** [phisher98/HindiProviders#75]
Many Hindi anime streaming sites are not working in Cloudsteam. AnimeDekho, Anplay and Tooniboy are not working.

Anime World and Toonstream are only two working sites but they have small collection of anime and cartoons.

https://animerulz.pro has huge collection of anime more than AnimeDekho.

It would be better if you add this site.

Please accept my request.

**Comment by phisher98** [comment]
There is no Anime Hindi Added in Codestream as I am aware also all Tooniboy, Toonstream, Anplay, Anime dekho working fine also Content library is also Nice which show are you looking for which you don't find in them and found on animerulz?

**Comment by ryan4021** [comment]
Okay my bad. But seriously AnimeDekho is not working on my TV and mobile it's keep saying "No Links Found", if it's working on your device then what's wrong with my device or is there any other problem?

**Comment by phisher98** [comment]
1.Make sure it's in Latest pre release.
2.It could be a issue with dns
3.Try to remove extension from extension of its downloaded from Hex repo and then download again from Hindi repo

**Comment by phisher98** [comment]
![Screenshot_2024-07-01-10-30-00-76_cfa2fd239c8cded9285432912d0e0818](https://github.com/phisher98/HindiProviders/assets/153359846/0d4b0e36-22a0-4977-9e57-0b5a94f23553)
Working no issues

**Comment by ryan4021** [comment]
> 1.Make sure it's in Latest pre release. 2.It could be a issue with dns 3.Try to remove extension from extension of its downloaded from Hex repo and then download again from Hindi repo

Thanks, it's working in the Beta version not the stable version.

**Comment by phisher98** [comment]
Yeah I thought so it's a Version issue now only use pre beta version it's mostly gets updated now
