### ISSUE TITLE
No Subtitles in Streamplay 

### ISSUE THREAD

**Issue by karanveers969** [phisher98/HindiProviders#79]
So recently there is a problem where no Subtitles load on streamplay (sorastream and codestream inlucuded)
https://www.reddit.com/r/Cloudstream3/s/E30cMgvsq2

**Comment by karanveers969** [comment]
![Uploading Screenshot_2024-07-07-13-14-08-41_cfa2fd239c8cded9285432912d0e0818.jpg…]()

**Comment by phisher98** [comment]
It's working fine no issues it may sometimes give issue because of api limits or something
