### ISSUE TITLE
Extention fix

### ISSUE THREAD

**Issue by ShankarKSH001** [phisher98/HindiProviders#80]
Can you fix MassTamilanProvider,  LikDev-256 already created extension for this but it not working now. 

Link : https://github.com/LikDev-256/likdev256-tamil-providers/tree/2e6b7d1332e2380332ef29ee2ff9a1cc6f816dfa/MassTamilanProvider

It shows: 
![Screenshot_20240707-155632](https://github.com/phisher98/HindiProviders/assets/121159747/1ff633fb-42c7-4e70-a58a-eebc993b6bde)

**Comment by phisher98** [comment]
Extension working fine just try to play it using VLC

**Comment by ShankarKSH001** [comment]
> Extension working fine just try to play it using  
Can you fix to play with cs3 if possible.

**Comment by ShankarKSH001** [comment]
> Extension working fine just try to play it using VLC

Can you fix to play with cs3 if possible

**Comment by phisher98** [comment]
I It's Functionality and stuff with exo player

**Comment by ShankarKSH001** [comment]
> I It's Functionality and stuff with exo player

I couldn't understand but it already played with cs3 with background movies posters.

**Comment by ShankarKSH001** [comment]
> I It's Functionality and stuff with exo player

Bro pls try to fix it, I enjoy this extension everyday  with cs3 internal player .

**Comment by phisher98** [comment]
My system is busted so I will not able to work on new extension for a while
