### ISSUE TITLE
Site request: tennistream

### ISSUE THREAD

**Issue by Rayforest** [phisher98/HindiProviders#82]
https://tennistream.com/

Pretty niche site with only tennis livestreams. If possible, do add when you get enough free time. Much love 🥰❤️

**Comment by phisher98** [comment]
Will check and if it's a Good source the will be Added

**Comment by Rayforest** [comment]
Thank you 🫂

**Comment by phisher98** [comment]
Added

**Comment by Rayforest** [comment]
> Added

Thank you so much. Lots of love 🥰🥰🥰🥰
