### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by ShankarKSH001** [phisher98/HindiProviders#83]
Site tamiyogi : https://tamilyogi.blog/tamilyogi/

**Comment by phisher98** [comment]
Cloudflare Protected not possible as of now

**Comment by phisher98** [comment]
Once you see Cloudflare removed request it again

**Comment by ShankarKSH001** [comment]
I don't know how to check cloud fare protected

**Comment by phisher98** [comment]
Okay I will keep this website in mind once cloudflare is removed I will try to add it but looks like it has only 720p content

**Comment by ShankarKSH001** [comment]
Oh really thanks bro you reply every requests great❤️‍🔥.

**Comment by phisher98** [comment]
![Uploading Screenshot_2024-07-15-14-57-02-04_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()
This is cloudflare Protected

**Comment by phisher98** [comment]
![Screenshot_2024-07-15-14-57-02-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/63ba9825-1fa2-4d22-b833-41c402f17cf2)
This is cloudflare Protected
