### ISSUE TITLE
Multimovies subtitle 

### ISSUE THREAD

**Issue by Rayforest** [phisher98/HindiProviders#87]
Is it possible to add the subtitles from multimovies to cs3?

**Comment by phisher98** [comment]
Not that I am aware of Not possible

**Comment by phisher98** [comment]
@Rayforest I have added Multimovies in Streamplay so you can select Source in Streamplay and it have Subtitles as well

**Comment by Rayforest** [comment]
> @Rayforest I have added Multimovies in Streamplay so you can select Source in Streamplay and it have Subtitles as well

Wow! That is awesome. Thank you so much! Btw which source has more links do you think, Streamplay or Codestream?

**Comment by phisher98** [comment]
I have no idea you have to use both and check for yourself
