### ISSUE TITLE
"Zshow" source missing in streamplay extension.

### ISSUE THREAD

**Issue by owengofficial** [phisher98/HindiProviders#88]
please fix many source missing in streamplay, and i begging you to always maintenance this extension, i always see many extension india you fixit,but you never maintenance extension english(streamplay). its not fair.

**Comment by artelxir** [comment]
Please request, don't demand. You're welcome to assist phisher98 in fixing the broken sources.

**Comment by karanveers969** [comment]
Streamplay uses a lot of sources so it's normal that a title is unavailable at some sources
If it doesn't work just try using a different extension

**Comment by SaurabhKaperwan** [comment]
Many of the hindi sources contained - content in dual audio English and Hindi. 
You can check them.
