### ISSUE TITLE
No Live Tv Extensions working 

### ISSUE THREAD

**Issue by karanveers969** [phisher98/HindiProviders#89]
As the title suggests, all the live tv extensions are very unstable rn they rarely work pls update them or add a better source

**Comment by karanveers969** [comment]
Pls add this 
https://tplay-all-beta.vercel.app/api/getM3u?sid=tplay_A&id=123456789&sname=tataP&tkn=xeotpxyastrplg

**Comment by phisher98** [comment]
There is no Good Reliable source and Sources with vercel app is also temp and as checked some are working and some don't so use NS player app or Tiwiplayer like apps
