### ISSUE TITLE
Hdmovie2

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/HindiProviders#90]
There are so many hindi websites in your extensions, but hdmovie2 were perfect because they were never buffering nor any bug comes. 

But there's a problem here they have no subtitles. 

I have a request to add subtitles in hdmovie2. 

Thanks for everything.

**Comment by phisher98** [comment]
Use Internet search for subtitles inbuilt in Player not possible to add it in Hdmovie

**Comment by Mrunknow3** [comment]
You can add like you add in streamply. Or you can also add hdmovie2 servers in streamply.

**Comment by phisher98** [comment]
I can try to add it in Streamplay once my laptop gets repaired it can take a long time

**Comment by Mrunknow3** [comment]
Oke

**Comment by adilurrhmn** [comment]
Fix this also .... 

![Uploading IMG_20240720_215444.jpg…]()

**Comment by adilurrhmn** [comment]
Fix this also

![IMG_20240720_215444](https://github.com/user-attachments/assets/488808da-9caa-4c61-a6a9-d0dc86aa1da4)

**Comment by phisher98** [comment]
That's not how it works It will remain same

**Comment by Mrunknow3** [comment]
Because of that always subtitles come one episode forward subtitles.

**Comment by phisher98** [comment]
Okay I will take a look at it if something could be done after laptop is fixed
