### ISSUE TITLE
Is this repo active? Many sites are not working including AnimeDekho and toonstream partially working

### ISSUE THREAD

**Issue by dewxo** [phisher98/HindiProviders#91]

**Comment by phisher98** [comment]
![Screenshot_2024-07-21-14-52-28-73_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/027efb1e-1b4c-470f-aead-71cf3dadc3e5)
![Screenshot_2024-07-21-14-51-13-81_cfa2fd239c8cded9285432912d0e0818](https://github.com/user-attachments/assets/7eb9b243-cfbb-4908-9603-512d1230765f)


Update App to pre release latest
