### ISSUE TITLE
Add support for Seedr video

### ISSUE THREAD

**Issue by Nexus-Gits** [phisher98/HindiProviders#95]
If anyway you support for [seedr](https://www.seedr.cc/) downloaded video play on Cloudstream.

Its plugin available for [kodi](https://github.com/DannyZB/seedr_kodi) and [Stremio](https://github.com/mhdzumair/MediaFusion). Also their api page [Seedr Api](https://www.seedr.cc/docs/api/rest/v1/#introduction).

I don't know if this possible or not. if possible then please add this feature in Cloudstream.

**Comment by phisher98** [comment]
Unrelated to extension Development
