### ISSUE TITLE
Multimovies plugin update

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#98]
Please update the plugin, when you try to play some latest movies like chhota bheem-The curse of damyan and kill, links are not loading but when you open the site there those are working properly.
Thanks

**Comment by phisher98** [comment]
It's working try to update your app to pre release or reload links 
![Screenshot_2024-07-28-10-01-59-592_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/0dcc1aef-ae9f-4b03-8839-385efaa4a3d6)

**Comment by Politecoder** [comment]
What is the app version that you are using ?

**Comment by Politecoder** [comment]
Thanks
