### ISSUE TITLE
Please add this site: Provider [https://hdmovies4u.foo/](https://hdmovies4u.foo/) for all HD quality movies and TV shows 📺, with Indian content 🇮🇳.

### ISSUE THREAD

**Issue by codeiva4u** [phisher98/HindiProviders#99]
This site is seriously the best It has lot of HD South Indian (Telugu, Tamil, Malayalam) content along with anime 🌝.
• https://hdmovies4u.foo/
Please add this in Repo 😭🙌

**Comment by mks32323232** [comment]
yes 
yes
yes

**Comment by phisher98** [comment]
It's already present in Streamplay/code stream just need to create a bypass for now it's on hold as it's difficult to create a bypass

**Comment by codeiva4u** [comment]
> It's already present in Streamplay/code stream just need to create a bypass for now it's on hold as it's difficult to create a bypass

I would like you to make it as a separate hdmovies4u provider 🙏🙏🙏

**Comment by codeiva4u** [comment]
You can create a bypass 
But it's hard for me to make a bypass

**Comment by phisher98** [comment]
Skill Issue unable to create bypass for it Closing for now
